pipeline {
           agent  any
               tools {
  terraform 'Terraform-v1'
  }
  stages{
      
         stage('git checkout'){
        steps{
               git 'https://github.com/NaushadPasha/nshd-learning.git'
             }
        }
     stage('Terraform Init'){
        steps{
           sh '''cd /home/ubuntu/adastra-test1
terraform init'''
             }
        }

stage('Terraform apply'){
        steps{
           sh '''cd /home/ubuntu/adastra-test1
/*terraform apply  --auto-approve -lock=false''' */
                   echo "The Script is running, Please update the pipeline to provision servers"
             }
        }

 } 

}  
