pipeline {
           agent  any
               tools {
  terraform 'Terraform-v1'
  }
  stages{
     

stage('Terraform Init'){
        steps{
           sh label: '',script: 'terraform apply --auto-approve'
             }
        }

 } 

}     
